# Build with "snapcraft" in the root of this directory.
# Then, sudo snap install --devmode ias-bash-script-infra_<version>_<arch>.snap

name: ias-bash-script-infra
version: '0.1'
summary: Bash infrastructure scripts and libraries
description: |
    Ticket URL: 
    Wiki Page: 

grade: stable
confinement: devmode
base: core18

# apps:
#     ias-bash-script-infra_hello.sh:
#         command: src/bin/ias-bash-script-infra_hello.sh

parts:
    snaptest1:
        plugin: dump
        source: ./src

